### ISSUE TITLE
Document the upgrade path from the component-nfs-client-provisioner

### ISSUE THREAD

**Issue by megian** [projectsyn/component-nfs-subdir-external-provisioner#2]
## Context

Document the upgrade path for clusters currently using the #component-nfs-client-provisioner.

The configuration needs to be changed from
```
applications:
  - nfs-client-provisioner

parameters::
  nfs_client_provisioner:
    path: /
    server: 10.0.0.1
```

to
```
applications:
  - nfs-client-provisioner

parameters:
  nfs_subdir_external_provisioner:
    helm_values:
      nfs:
        server: 10.0.0.1
        path: /
```

Test what the impact of changing the provisionername from cluster.local/platform-nfs-client-provisioner to cluster.local/platform-nfs-subdir-external-provisioner has to existing PVs, when they got deleted.
